// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetXfwCtKey struct {
	_        structs.HostLayout
	SrcIp    NetXfwIn6Addr
	DstIp    NetXfwIn6Addr
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type NetXfwCtValue struct {
	_        structs.HostLayout
	LastSeen uint64
}

type NetXfwIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type NetXfwLpmIpPortKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Pad       uint16
	Port      uint16
	Ip        NetXfwIn6Addr
}

type NetXfwLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      NetXfwIn6Addr
}

type NetXfwRatelimitValue struct {
	_             structs.HostLayout
	Rate          uint64
	RateScaled    uint64
	Burst         uint64
	ConfigVersion uint64
	LastTime      uint64
	Tokens        uint64
}

type NetXfwRuleValue struct {
	_         structs.HostLayout
	Counter   uint64
	ExpiresAt uint64
	Action    uint8
	Priority  uint8
	Pad       [6]uint8
}

type NetXfwStatsGlobal struct {
	_               structs.HostLayout
	TotalPackets    uint64
	TotalPass       uint64
	TotalDrop       uint64
	DropBlacklist   uint64
	DropNoRule      uint64
	DropInvalid     uint64
	DropRateLimit   uint64
	DropSynFlood    uint64
	DropIcmpLimit   uint64
	DropPortBlocked uint64
	DropDefaultDeny uint64
	PassWhitelist   uint64
	PassRule        uint64
	PassReturn      uint64
	PassEstablished uint64
	IcmpLastTime    uint64
	IcmpTokens      uint64
	ConfigVersion   uint64
	Reserved        [8]uint64
}

type NetXfwTopStatsKey struct {
	_        structs.HostLayout
	Reason   uint32
	Protocol uint32
	SrcIp    NetXfwIn6Addr
	DstPort  uint16
	Pad      uint16
}

// LoadNetXfw returns the embedded CollectionSpec for NetXfw.
func LoadNetXfw() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetXfwBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetXfw: %w", err)
	}

	return spec, err
}

// LoadNetXfwObjects loads NetXfw and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetXfwObjects
//	*NetXfwPrograms
//	*NetXfwMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetXfwObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetXfw()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetXfwSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetXfwSpecs struct {
	NetXfwProgramSpecs
	NetXfwMapSpecs
	NetXfwVariableSpecs
}

// NetXfwProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetXfwProgramSpecs struct {
	TcEgress            *ebpf.ProgramSpec `ebpf:"tc_egress"`
	XdpBlacklist        *ebpf.ProgramSpec `ebpf:"xdp_blacklist"`
	XdpConntrack        *ebpf.ProgramSpec `ebpf:"xdp_conntrack"`
	XdpCritical         *ebpf.ProgramSpec `ebpf:"xdp_critical"`
	XdpDynamicBlacklist *ebpf.ProgramSpec `ebpf:"xdp_dynamic_blacklist"`
	XdpFirewall         *ebpf.ProgramSpec `ebpf:"xdp_firewall"`
	XdpIcmp             *ebpf.ProgramSpec `ebpf:"xdp_icmp"`
	XdpIpv4             *ebpf.ProgramSpec `ebpf:"xdp_ipv4"`
	XdpIpv6             *ebpf.ProgramSpec `ebpf:"xdp_ipv6"`
	XdpRatelimit        *ebpf.ProgramSpec `ebpf:"xdp_ratelimit"`
	XdpReturn           *ebpf.ProgramSpec `ebpf:"xdp_return"`
	XdpRules            *ebpf.ProgramSpec `ebpf:"xdp_rules"`
	XdpSanity           *ebpf.ProgramSpec `ebpf:"xdp_sanity"`
	XdpWhitelist        *ebpf.ProgramSpec `ebpf:"xdp_whitelist"`
}

// NetXfwMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetXfwMapSpecs struct {
	ChainMap          *ebpf.MapSpec `ebpf:"chain_map"`
	ConntrackMap      *ebpf.MapSpec `ebpf:"conntrack_map"`
	CriticalBlacklist *ebpf.MapSpec `ebpf:"critical_blacklist"`
	DynamicBlacklist  *ebpf.MapSpec `ebpf:"dynamic_blacklist"`
	GlobalConfig      *ebpf.MapSpec `ebpf:"global_config"`
	JmpTable          *ebpf.MapSpec `ebpf:"jmp_table"`
	RatelimitMap      *ebpf.MapSpec `ebpf:"ratelimit_map"`
	RuleMap           *ebpf.MapSpec `ebpf:"rule_map"`
	StaticBlacklist   *ebpf.MapSpec `ebpf:"static_blacklist"`
	StatsGlobalMap    *ebpf.MapSpec `ebpf:"stats_global_map"`
	TopDropMap        *ebpf.MapSpec `ebpf:"top_drop_map"`
	TopPassMap        *ebpf.MapSpec `ebpf:"top_pass_map"`
	Whitelist         *ebpf.MapSpec `ebpf:"whitelist"`
	XskMap            *ebpf.MapSpec `ebpf:"xsk_map"`
}

// NetXfwVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetXfwVariableSpecs struct {
	CachedAfXdpEnabled     *ebpf.VariableSpec `ebpf:"cached_af_xdp_enabled"`
	CachedAllowIcmp        *ebpf.VariableSpec `ebpf:"cached_allow_icmp"`
	CachedAllowReturn      *ebpf.VariableSpec `ebpf:"cached_allow_return"`
	CachedAutoBlock        *ebpf.VariableSpec `ebpf:"cached_auto_block"`
	CachedAutoBlockExpiry  *ebpf.VariableSpec `ebpf:"cached_auto_block_expiry"`
	CachedBogonFilter      *ebpf.VariableSpec `ebpf:"cached_bogon_filter"`
	CachedCtEnabled        *ebpf.VariableSpec `ebpf:"cached_ct_enabled"`
	CachedCtTimeout        *ebpf.VariableSpec `ebpf:"cached_ct_timeout"`
	CachedDefaultDeny      *ebpf.VariableSpec `ebpf:"cached_default_deny"`
	CachedDropFrags        *ebpf.VariableSpec `ebpf:"cached_drop_frags"`
	CachedIcmpBurst        *ebpf.VariableSpec `ebpf:"cached_icmp_burst"`
	CachedIcmpRate         *ebpf.VariableSpec `ebpf:"cached_icmp_rate"`
	CachedRatelimitEnabled *ebpf.VariableSpec `ebpf:"cached_ratelimit_enabled"`
	CachedStrictProto      *ebpf.VariableSpec `ebpf:"cached_strict_proto"`
	CachedStrictTcp        *ebpf.VariableSpec `ebpf:"cached_strict_tcp"`
	CachedSynLimit         *ebpf.VariableSpec `ebpf:"cached_syn_limit"`
	CachedVersion          *ebpf.VariableSpec `ebpf:"cached_version"`
}

// NetXfwObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetXfwObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetXfwObjects struct {
	NetXfwPrograms
	NetXfwMaps
	NetXfwVariables
}

func (o *NetXfwObjects) Close() error {
	return _NetXfwClose(
		&o.NetXfwPrograms,
		&o.NetXfwMaps,
	)
}

// NetXfwMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetXfwObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetXfwMaps struct {
	ChainMap          *ebpf.Map `ebpf:"chain_map"`
	ConntrackMap      *ebpf.Map `ebpf:"conntrack_map"`
	CriticalBlacklist *ebpf.Map `ebpf:"critical_blacklist"`
	DynamicBlacklist  *ebpf.Map `ebpf:"dynamic_blacklist"`
	GlobalConfig      *ebpf.Map `ebpf:"global_config"`
	JmpTable          *ebpf.Map `ebpf:"jmp_table"`
	RatelimitMap      *ebpf.Map `ebpf:"ratelimit_map"`
	RuleMap           *ebpf.Map `ebpf:"rule_map"`
	StaticBlacklist   *ebpf.Map `ebpf:"static_blacklist"`
	StatsGlobalMap    *ebpf.Map `ebpf:"stats_global_map"`
	TopDropMap        *ebpf.Map `ebpf:"top_drop_map"`
	TopPassMap        *ebpf.Map `ebpf:"top_pass_map"`
	Whitelist         *ebpf.Map `ebpf:"whitelist"`
	XskMap            *ebpf.Map `ebpf:"xsk_map"`
}

func (m *NetXfwMaps) Close() error {
	return _NetXfwClose(
		m.ChainMap,
		m.ConntrackMap,
		m.CriticalBlacklist,
		m.DynamicBlacklist,
		m.GlobalConfig,
		m.JmpTable,
		m.RatelimitMap,
		m.RuleMap,
		m.StaticBlacklist,
		m.StatsGlobalMap,
		m.TopDropMap,
		m.TopPassMap,
		m.Whitelist,
		m.XskMap,
	)
}

// NetXfwVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetXfwObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetXfwVariables struct {
	CachedAfXdpEnabled     *ebpf.Variable `ebpf:"cached_af_xdp_enabled"`
	CachedAllowIcmp        *ebpf.Variable `ebpf:"cached_allow_icmp"`
	CachedAllowReturn      *ebpf.Variable `ebpf:"cached_allow_return"`
	CachedAutoBlock        *ebpf.Variable `ebpf:"cached_auto_block"`
	CachedAutoBlockExpiry  *ebpf.Variable `ebpf:"cached_auto_block_expiry"`
	CachedBogonFilter      *ebpf.Variable `ebpf:"cached_bogon_filter"`
	CachedCtEnabled        *ebpf.Variable `ebpf:"cached_ct_enabled"`
	CachedCtTimeout        *ebpf.Variable `ebpf:"cached_ct_timeout"`
	CachedDefaultDeny      *ebpf.Variable `ebpf:"cached_default_deny"`
	CachedDropFrags        *ebpf.Variable `ebpf:"cached_drop_frags"`
	CachedIcmpBurst        *ebpf.Variable `ebpf:"cached_icmp_burst"`
	CachedIcmpRate         *ebpf.Variable `ebpf:"cached_icmp_rate"`
	CachedRatelimitEnabled *ebpf.Variable `ebpf:"cached_ratelimit_enabled"`
	CachedStrictProto      *ebpf.Variable `ebpf:"cached_strict_proto"`
	CachedStrictTcp        *ebpf.Variable `ebpf:"cached_strict_tcp"`
	CachedSynLimit         *ebpf.Variable `ebpf:"cached_syn_limit"`
	CachedVersion          *ebpf.Variable `ebpf:"cached_version"`
}

// NetXfwPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetXfwObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetXfwPrograms struct {
	TcEgress            *ebpf.Program `ebpf:"tc_egress"`
	XdpBlacklist        *ebpf.Program `ebpf:"xdp_blacklist"`
	XdpConntrack        *ebpf.Program `ebpf:"xdp_conntrack"`
	XdpCritical         *ebpf.Program `ebpf:"xdp_critical"`
	XdpDynamicBlacklist *ebpf.Program `ebpf:"xdp_dynamic_blacklist"`
	XdpFirewall         *ebpf.Program `ebpf:"xdp_firewall"`
	XdpIcmp             *ebpf.Program `ebpf:"xdp_icmp"`
	XdpIpv4             *ebpf.Program `ebpf:"xdp_ipv4"`
	XdpIpv6             *ebpf.Program `ebpf:"xdp_ipv6"`
	XdpRatelimit        *ebpf.Program `ebpf:"xdp_ratelimit"`
	XdpReturn           *ebpf.Program `ebpf:"xdp_return"`
	XdpRules            *ebpf.Program `ebpf:"xdp_rules"`
	XdpSanity           *ebpf.Program `ebpf:"xdp_sanity"`
	XdpWhitelist        *ebpf.Program `ebpf:"xdp_whitelist"`
}

func (p *NetXfwPrograms) Close() error {
	return _NetXfwClose(
		p.TcEgress,
		p.XdpBlacklist,
		p.XdpConntrack,
		p.XdpCritical,
		p.XdpDynamicBlacklist,
		p.XdpFirewall,
		p.XdpIcmp,
		p.XdpIpv4,
		p.XdpIpv6,
		p.XdpRatelimit,
		p.XdpReturn,
		p.XdpRules,
		p.XdpSanity,
		p.XdpWhitelist,
	)
}

func _NetXfwClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netxfw_bpfeb.o
var _NetXfwBytes []byte
