.PHONY: build build-compressed generate clean

VERSION ?= $(shell git describe --tags --always --dirty)
COMMIT  ?= $(shell git rev-parse --short HEAD)

BPF_CFLAGS :=
# Default to ipv6=yes if not specified
ipv6 ?= yes

# Check if ipv6 is enabled (1, yes, true, on)
ifeq ($(filter $(ipv6),1 yes true on YES TRUE ON),$(ipv6))
	BPF_CFLAGS += -DENABLE_IPV6
endif

help:
	@echo "  make build           - Build binary (stripped)"
	@echo "  make build-compressed - Build binary with UPX compression (smallest)"
	@echo "  make generate        - Generate BPF code"
	@echo "  make fmt             - Format Go code"
	@echo "  make lint            - Run golangci-lint"
	@echo "  make install         - Install binary and config"
	@echo "  make uninstall       - Remove binary and config"
	@echo "  make clean           - Clean build artifacts"

build:
	go build -ldflags="-s -w -X 'github.com/netxfw/netxfw/internal/version.Version=$(VERSION)' -X 'github.com/netxfw/netxfw/internal/version.GitCommit=$(COMMIT)'" -trimpath -o netxfw ./cmd/netxfw

# Default build target with dev version
build-dev:
	go build -ldflags="-s -w -X 'github.com/netxfw/netxfw/internal/version.Version=dev'" -trimpath -o netxfw ./cmd/netxfw

build-compressed: build
	@echo "Compressing binary with UPX..."
	upx --best netxfw
	@echo "✅ Binary compressed successfully"

generate:
	@echo "/* Automatically generated by Makefile. Do not edit. */" > bpf/include/bpf_features.h
	@echo "#ifndef __NETXFW_FEATURES_H" >> bpf/include/bpf_features.h
	@echo "#define __NETXFW_FEATURES_H" >> bpf/include/bpf_features.h
ifeq ($(filter $(ipv6),1 yes true on YES TRUE ON),$(ipv6))
	@echo "#define ENABLE_IPV6" >> bpf/include/bpf_features.h
	@echo "✅ IPv6 enabled in BPF"
else
	@echo "//#define ENABLE_IPV6" >> bpf/include/bpf_features.h
	@echo "⚠️  IPv6 disabled in BPF"
endif
	@echo "#endif" >> bpf/include/bpf_features.h
	cd internal/xdp && go generate

fmt:
	go fmt ./...

lint:
	golangci-lint run

plugins:
	@mkdir -p bpf/plugins/out
	@for f in bpf/plugins/*.bpf.c; do \
		name=$$(basename $$f .bpf.c); \
		echo "Compiling plugin: $$name"; \
		clang -g -O3 -target bpf -D__TARGET_ARCH_x86 -I/usr/include/x86_64-linux-gnu -I./bpf -I./bpf/include $(BPF_CFLAGS) -c $$f -o bpf/plugins/out/$$name.o; \
	done
	@echo "✅ Plugins compiled to bpf/plugins/out/ (Optimized with -O3)"

install: build
	mkdir -p /etc/netxfw
	mkdir -p /usr/local/bin
	cp netxfw /usr/local/bin/
	if [ ! -f /etc/netxfw/config.yaml ]; then cp rules/default.yaml /etc/netxfw/config.yaml; fi
	if [ ! -f /etc/netxfw/lock_list.txt ]; then touch /etc/netxfw/lock_list.txt; fi

uninstall:
	rm -f /usr/local/bin/netxfw
	rm -rf /sys/fs/bpf/netxfw

clean:
	rm -f netxfw
	rm -f *.o
