.PHONY: build generate clean

BPF_CFLAGS :=
# Default to ipv6=yes if not specified
ipv6 ?= yes

# Check if ipv6 is enabled (1, yes, true, on)
ifeq ($(filter $(ipv6),1 yes true on YES TRUE ON),$(ipv6))
	BPF_CFLAGS += -DENABLE_IPV6
endif

help:
	@echo "  make uninstall   - Remove binary and config"
	@echo "  make clean       - Clean build artifacts"

build:
	go build -o netxfw ./cmd/netxfw

generate:
	@echo "/* Automatically generated by Makefile. Do not edit. */" > bpf/include/bpf_features.h
	@echo "#ifndef __NETXFW_FEATURES_H" >> bpf/include/bpf_features.h
	@echo "#define __NETXFW_FEATURES_H" >> bpf/include/bpf_features.h
ifeq ($(filter $(ipv6),1 yes true on YES TRUE ON),$(ipv6))
	@echo "#define ENABLE_IPV6" >> bpf/include/bpf_features.h
	@echo "✅ IPv6 enabled in BPF"
else
	@echo "//#define ENABLE_IPV6" >> bpf/include/bpf_features.h
	@echo "⚠️  IPv6 disabled in BPF"
endif
	@echo "#endif" >> bpf/include/bpf_features.h
	cd internal/xdp && go generate

plugins:
	@mkdir -p bpf/plugins/out
	@for f in bpf/plugins/*.bpf.c; do \
		name=$$(basename $$f .bpf.c); \
		echo "Compiling plugin: $$name"; \
		clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I/usr/include/x86_64-linux-gnu -I./bpf -I./bpf/include $(BPF_CFLAGS) -c $$f -o bpf/plugins/out/$$name.o; \
	done
	@echo "✅ Plugins compiled to bpf/plugins/out/"

install: build
	mkdir -p /etc/netxfw
	mkdir -p /usr/local/bin
	cp netxfw /usr/local/bin/
	if [ ! -f /etc/netxfw/config.yaml ]; then cp rules/default.yaml /etc/netxfw/config.yaml; fi
	if [ ! -f /etc/netxfw/lock_list.txt ]; then touch /etc/netxfw/lock_list.txt; fi

uninstall:
	rm -f /usr/local/bin/netxfw
	rm -rf /sys/fs/bpf/netxfw

clean:
	rm -f netxfw
	rm -f *.o
