.PHONY: build build-compressed generate clean build-zig-amd64 build-zig-arm64 test lint check bench bench-baseline bench-regression docs-check

BPF_CFLAGS :=
PREFIX ?= /usr/local
ETCDIR ?= /etc/netxfw
DESTDIR ?=
CLANG ?= clang
BPF_ARCH_INCLUDE ?= /usr/include/x86_64-linux-gnu
# Zig compiler configuration
ZIG_CC := zig cc
ZIG_TARGET_AMD64 := x86_64-linux-gnu.2.17
ZIG_TARGET_ARM64 := aarch64-linux-gnu.2.17

# Default to ipv6=yes if not specified
ipv6 ?= yes

# Check if ipv6 is enabled (1, yes, true, on)
ifeq ($(filter $(ipv6),1 yes true on YES TRUE ON),$(ipv6))
	BPF_CFLAGS += -DENABLE_IPV6
endif

help:
	@echo "  make build            - Build binary (stripped)"
	@echo "  make build-zig-amd64  - Build binary using Zig (amd64, glibc 2.17)"
	@echo "  make build-zig-arm64  - Build binary using Zig (arm64, glibc 2.17)"
	@echo "  make build-compressed - Build binary with UPX compression (smallest)"
	@echo "  make generate         - Generate BPF code (requires Go toolchain)"
	@echo "  make test             - Run fast test suite"
	@echo "  make lint             - Run static checks"
	@echo "  make docs-check       - Run docs link + CLI call-graph checks"
	@echo "  make check            - Run architecture, lint, build and test checks"
	@echo "  make bench            - Run benchmark tests"
	@echo "  make bench-baseline   - Create performance baseline"
	@echo "  make bench-regression - Run performance regression tests"
	@echo "  make plugins          - Compile BPF plugins (requires $(CLANG))"
	@echo "  make install          - Install binary and config (supports PREFIX/ETCDIR/DESTDIR)"
	@echo "  make uninstall        - Remove binary and config from DESTDIR/PREFIX"
	@echo "  make clean            - Clean build artifacts"

build:
	go build -ldflags="-s -w -X 'github.com/netxfw/netxfw/internal/version.Version=$(VERSION)' -X 'github.com/netxfw/netxfw/internal/version.GitCommit=$(COMMIT)'" -trimpath -o netxfw ./cmd/netxfw

# Build with Zig for amd64
build-zig-amd64:
	CGO_ENABLED=1 CC="$(ZIG_CC) -target $(ZIG_TARGET_AMD64)" \
	go build -ldflags="-s -w -X 'github.com/netxfw/netxfw/internal/version.Version=$(VERSION)'" \
	-trimpath -o netxfw-amd64 ./cmd/netxfw

# Build with Zig for arm64
build-zig-arm64:
	CGO_ENABLED=1 CC="$(ZIG_CC) -target $(ZIG_TARGET_ARM64)" \
	go build -ldflags="-s -w -X 'github.com/netxfw/netxfw/internal/version.Version=$(VERSION)'" \
	-trimpath -o netxfw-arm64 ./cmd/netxfw

# Default build target with dev version
build-dev:
	go build -ldflags="-s -w -X 'github.com/netxfw/netxfw/internal/version.Version=dev'" -trimpath -o netxfw ./cmd/netxfw

build-compressed: build
	@echo "Compressing binary with UPX..."
	upx --best netxfw
	@echo "✅ Binary compressed successfully"

generate:
	@echo "/* Automatically generated by Makefile. Do not edit. */" > bpf/include/bpf_features.h
	@echo "#ifndef __NETXFW_FEATURES_H" >> bpf/include/bpf_features.h
	@echo "#define __NETXFW_FEATURES_H" >> bpf/include/bpf_features.h
ifeq ($(filter $(ipv6),1 yes true on YES TRUE ON),$(ipv6))
	@echo "#define ENABLE_IPV6" >> bpf/include/bpf_features.h
	@echo "✅ IPv6 enabled in BPF"
else
	@echo "//#define ENABLE_IPV6" >> bpf/include/bpf_features.h
	@echo "⚠️  IPv6 disabled in BPF"
endif
	@echo "#endif" >> bpf/include/bpf_features.h
	go generate ./internal/datapath/xdp/backend

test:
	go test ./test/unit/... ./internal/... ./cmd/... ./pkg/...

lint:
	golangci-lint run --timeout=5m
	go run github.com/fzipp/gocyclo/cmd/gocyclo@latest -over 15 ./internal/api/auth.go
	go run github.com/fzipp/gocyclo/cmd/gocyclo@latest -over 30 ./internal/api
	go run github.com/fzipp/gocyclo/cmd/gocyclo@latest -over 18 ./internal/datapath
	go run github.com/fzipp/gocyclo/cmd/gocyclo@latest -over 15 ./internal/plugins

check:
	bash ./scripts/check_markdown_links.sh
	bash ./scripts/check_cli_callgraphs.sh
	bash ./scripts/check_architecture.sh
	$(MAKE) lint
	go build -trimpath ./cmd/netxfw
	$(MAKE) test

docs-check:
	bash ./docs/check_links.sh
	bash ./scripts/check_cli_callgraphs.sh

bench:
	go test -bench=. ./test/performance/...

bench-baseline:
	@echo "📊 Creating performance baseline..."
	@mkdir -p $(HOME)/.netxfw/benchmarks
	go test -bench=. -benchmem -run=^$ ./test/performance/... 2>&1 | tee $(HOME)/.netxfw/benchmarks/bench_output.txt
	@if [ -f $(HOME)/.netxfw/benchmarks/results.json ]; then \
		cp $(HOME)/.netxfw/benchmarks/results.json $(HOME)/.netxfw/benchmarks/baseline.json; \
		echo "✅ Baseline saved to $(HOME)/.netxfw/benchmarks/baseline.json"; \
	else \
		echo '{}' > $(HOME)/.netxfw/benchmarks/baseline.json; \
		echo "✅ Empty baseline created"; \
	fi

bench-regression:
	@echo "📈 Running performance regression tests..."
	@bash ./scripts/bench_regression.sh

plugins:
	@mkdir -p bpf/plugins/out
	@for f in bpf/plugins/*.bpf.c; do \
		name=$$(basename $$f .bpf.c); \
		echo "Compiling plugin: $$name"; \
		$(CLANG) -g -O2 -target bpf -D__TARGET_ARCH_x86 -I$(BPF_ARCH_INCLUDE) -I./bpf -I./bpf/include $(BPF_CFLAGS) -c $$f -o bpf/plugins/out/$$name.o; \
	done
	@echo "✅ Plugins compiled to bpf/plugins/out/"

install: build
	mkdir -p "$(DESTDIR)$(ETCDIR)"
	mkdir -p "$(DESTDIR)$(PREFIX)/bin"
	cp netxfw "$(DESTDIR)$(PREFIX)/bin/"
	if [ ! -f "$(DESTDIR)$(ETCDIR)/config.yaml" ]; then ./netxfw system init --config "$(DESTDIR)$(ETCDIR)/config.yaml"; fi
	if [ ! -f "$(DESTDIR)$(ETCDIR)/lock_list.txt" ]; then touch "$(DESTDIR)$(ETCDIR)/lock_list.txt"; fi

uninstall:
	rm -f "$(DESTDIR)$(PREFIX)/bin/netxfw"
	rm -rf "$(DESTDIR)/sys/fs/bpf/netxfw"

clean:
	rm -f netxfw
	rm -f *.o
