// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NetXfwLpmKey4 struct {
	Prefixlen uint32
	Data      uint32
}

type NetXfwLpmKey6 struct {
	Prefixlen uint32
	Data      struct{ In6U struct{ U6Addr8 [16]uint8 } }
}

// LoadNetXfw returns the embedded CollectionSpec for NetXfw.
func LoadNetXfw() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetXfwBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetXfw: %w", err)
	}

	return spec, err
}

// LoadNetXfwObjects loads NetXfw and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetXfwObjects
//	*NetXfwPrograms
//	*NetXfwMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetXfwObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetXfw()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetXfwSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetXfwSpecs struct {
	NetXfwProgramSpecs
	NetXfwMapSpecs
}

// NetXfwSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetXfwProgramSpecs struct {
	XdpFirewall *ebpf.ProgramSpec `ebpf:"xdp_firewall"`
}

// NetXfwMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetXfwMapSpecs struct {
	DropStats  *ebpf.MapSpec `ebpf:"drop_stats"`
	LockList   *ebpf.MapSpec `ebpf:"lock_list"`
	LockList6  *ebpf.MapSpec `ebpf:"lock_list6"`
	Whitelist  *ebpf.MapSpec `ebpf:"whitelist"`
	Whitelist6 *ebpf.MapSpec `ebpf:"whitelist6"`
}

// NetXfwObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetXfwObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetXfwObjects struct {
	NetXfwPrograms
	NetXfwMaps
}

func (o *NetXfwObjects) Close() error {
	return _NetXfwClose(
		&o.NetXfwPrograms,
		&o.NetXfwMaps,
	)
}

// NetXfwMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetXfwObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetXfwMaps struct {
	DropStats  *ebpf.Map `ebpf:"drop_stats"`
	LockList   *ebpf.Map `ebpf:"lock_list"`
	LockList6  *ebpf.Map `ebpf:"lock_list6"`
	Whitelist  *ebpf.Map `ebpf:"whitelist"`
	Whitelist6 *ebpf.Map `ebpf:"whitelist6"`
}

func (m *NetXfwMaps) Close() error {
	return _NetXfwClose(
		m.DropStats,
		m.LockList,
		m.LockList6,
		m.Whitelist,
		m.Whitelist6,
	)
}

// NetXfwPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetXfwObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetXfwPrograms struct {
	XdpFirewall *ebpf.Program `ebpf:"xdp_firewall"`
}

func (p *NetXfwPrograms) Close() error {
	return _NetXfwClose(
		p.XdpFirewall,
	)
}

func _NetXfwClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netxfw_bpfel.o
var _NetXfwBytes []byte
