/* Automatically generated by Makefile. Do not edit. */
#ifndef __NETXFW_FEATURES_H
#define __NETXFW_FEATURES_H
#define ENABLE_IPV6

// Drop Reasons
#define DROP_REASON_UNKNOWN 0
#define DROP_REASON_BLACKLIST 1
#define DROP_REASON_RATELIMIT 2
#define DROP_REASON_PROTOCOL 3
#define DROP_REASON_INVALID 4
#define DROP_REASON_DEFAULT 5
#define DROP_REASON_DYN_BLACKLIST 6
#define DROP_REASON_STRICT_TCP 7
#define DROP_REASON_GEOIP 8

#endif
