# netxfw 配置文件
# -----------------

# 动态拦截规则配置
rules:
  - name: ssh_bruteforce # 规则名称
    port: 22             # 监控端口
    threshold: 5         # 触发阈值（如：单位时间内连接次数）
    duration: "1h"       # 封禁时长
  - name: web_scan
    port: 80
    threshold: 20
    duration: "30m"

# 白名单配置：此列表中的 IP 或网段将永远不会被拦截
# 支持单个 IP (如 "192.168.1.1") 或 CIDR 网段 (如 "192.168.1.0/24")
whitelist:
  - "127.0.0.1"
  - "::1"
  - "192.168.1.0/24"
  - "10.0.0.0/8"

# Prometheus 指标服务监听端口
metrics_port: 9100